import { Audit } from './types';
export const demoAudit: Audit = {
  id:'demo_schema_audit',projectName:'Demo data — not a live audit',url:'https://www.example.com/city/rome',domain:'https://www.example.com',mode:'Single URL Audit',auditedAt:'2026-08-25T10:00:00.000Z',isDemo:true,
  page:{title:'Private Tours in Rome',h1:'Explore Rome with Local Guides',description:'Representative demo city page.',canonical:'https://www.example.com/city/rome',pageType:'City page',confidence:92,evidence:['URL pattern contains a city hierarchy.','H1 identifies Rome as the main destination.','Visible cards form a collection of experiences.'],alternate:'CollectionPage'},
  schemaItems:[{id:'demo_schema_1',format:'JSON-LD',type:['WebPage','BreadcrumbList'],nodeId:'https://www.example.com/city/rome/#webpage',properties:{'@context':'https://schema.org','@graph':[{'@type':'WebPage','@id':'https://www.example.com/city/rome/#webpage',name:'Private Tours in Rome'},{'@type':'BreadcrumbList','itemListElement':[]}]},parseStatus:'Valid',googleEligibility:'Breadcrumb feature requires complete visible items',schemaValidity:'Pass',visibleMatch:'Needs review',errors:[],warnings:['WebPage lacks isPartOf and about.']}],
  requirements:[
    {schemaType:'WebPage',level:'Required for site model',ecosystem:'Schema.org semantics',properties:['@id','url','name','isPartOf','about'],missing:['url','isPartOf','about'],reason:'Connect the page to the site graph and primary city entity.'},
    {schemaType:'City',level:'Recommended',ecosystem:'Entity relationship',properties:['@id','name','sameAs'],missing:['@id','name','sameAs'],reason:'Describe the exact city entity; sameAs requires identity approval.'},
    {schemaType:'ItemList',level:'Conditional',ecosystem:'Google-supported rich result',properties:['itemListElement'],missing:['itemListElement'],reason:'Use only for tours visibly listed on the page.'}
  ],
  issues:[{id:'demo_issue_1',severity:'High',category:'Entity graph',title:'Primary city entity is missing',evidence:'The page visibly centres on Rome but WebPage.about is absent.',recommendation:'Add a City node and reference it through WebPage.about after exact Wikidata approval.',scope:'Template'},{id:'demo_issue_2',severity:'Medium',category:'Graph relationship',title:'WebPage is disconnected from WebSite',evidence:'No isPartOf reference was found.',recommendation:'Reference the stable #website node with isPartOf.',scope:'Template'},{id:'demo_issue_3',severity:'Medium',category:'Content prerequisite',title:'Visible list must be verified',evidence:'ItemList eligibility depends on the cards rendered to users.',recommendation:'Map only visible tour cards and their canonical URLs.',scope:'Content prerequisite'}],
  entities:[{id:'demo_entity_1',name:'Rome',type:'City',role:'Primary subject',evidence:'Title, H1 and destination content',salience:'High',property:'about',candidateWikipedia:'https://en.wikipedia.org/wiki/Rome',candidateWikidata:'https://www.wikidata.org/wiki/Q220',identityStatus:'Exact verified match',approved:true},{id:'demo_entity_2',name:'Pantheon',type:'TouristAttraction',role:'Secondary mention',evidence:'Visible attraction section',salience:'Medium',property:'mentions',candidateWikipedia:'https://en.wikipedia.org/wiki/Pantheon,_Rome',candidateWikidata:'https://www.wikidata.org/wiki/Q99309',identityStatus:'Strong probable match',approved:false},{id:'demo_entity_3',name:'Local guide named Alex',type:'Person',role:'Secondary mention',evidence:'Visible guide card',salience:'Low',property:'No markup',identityStatus:'Ambiguous',approved:false}],
  recommendation:{'@context':'https://schema.org','@graph':[{'@type':'WebSite','@id':'https://www.example.com/#website','url':'https://www.example.com','name':'[VERIFIED SITE NAME REQUIRED]'},{'@type':'WebPage','@id':'https://www.example.com/city/rome/#webpage','url':'https://www.example.com/city/rome','name':'Private Tours in Rome','isPartOf':{'@id':'https://www.example.com/#website'},'about':{'@id':'https://www.example.com/city/rome/#city'}},{'@type':'City','@id':'https://www.example.com/city/rome/#city','name':'Rome','sameAs':['https://www.wikidata.org/wiki/Q220','https://en.wikipedia.org/wiki/Rome']}]},
  validation:[{name:'JSON-LD valid',state:'Pass',details:'The recommendation parses as valid JSON.'},{name:'Schema.org valid',state:'Pass',details:'Types and properties are semantically compatible.'},{name:'Google-required fields complete',state:'Not applicable',details:'City entity markup is not a standalone Google rich result.'},{name:'Entity identities verified',state:'Needs review',details:'Rome is approved; Pantheon and person candidates remain unapproved.'},{name:'Visible-content consistency passed',state:'Needs review',details:'Confirm visible tour cards before adding ItemList.'},{name:'Production ready',state:'Fail',details:'One verified site-name placeholder remains.'}],
  executiveSummary:['The page currently contains a valid but disconnected WebPage and BreadcrumbList graph.','A primary City entity and WebPage.about relationship are missing.','Rome has an exact verified identity; the Pantheon candidate requires approval.','ItemList is conditional on visible tour cards and exact canonical URLs.'],
  implementation:[{priority:'High',action:'Create the City node and connect it through WebPage.about.','owner':'SEO / Development',effort:'Low',acceptance:'The exact Rome identity is referenced from the canonical page node.'},{priority:'Medium',action:'Connect WebPage to the stable WebSite node.','owner':'Development',effort:'Low',acceptance:'One reusable #website identity is referenced.'},{priority:'Medium',action:'Verify visible tour-card data before ItemList implementation.','owner':'Content / Development',effort:'Medium',acceptance:'Every ItemList item exists visibly and uses its canonical URL.'}]
};
