export type Severity = 'Critical'|'High'|'Medium'|'Low'|'Informational';
export type ValidationState = 'Pass'|'Fail'|'Needs review'|'Not applicable';
export interface SchemaItem { id:string; format:'JSON-LD'|'Microdata'|'RDFa'; type:string[]; nodeId?:string; properties:Record<string,unknown>; parseStatus:'Valid'|'Invalid'; googleEligibility:string; schemaValidity:ValidationState; visibleMatch:ValidationState; errors:string[]; warnings:string[] }
export interface Requirement { schemaType:string; level:'Required for site model'|'Required for Google eligibility'|'Recommended'|'Optional'|'Conditional'|'Not recommended'; ecosystem:'Google-supported rich result'|'Schema.org semantics'|'Entity relationship'|'Sitewide identity'; properties:string[]; missing:string[]; reason:string; prerequisite?:string }
export interface Issue { id:string; severity:Severity; category:string; title:string; evidence:string; recommendation:string; scope:'URL'|'Template'|'Sitewide'|'Data source'|'Content prerequisite' }
export interface Entity { id:string; name:string; type:string; role:'Primary subject'|'Main entity'|'Secondary mention'|'Incidental mention'|'Organisation identity'|'Author identity'; evidence:string; salience:'High'|'Medium'|'Low'; property:'about'|'mentions'|'mainEntity'|'sameAs'|'knowsAbout'|'No markup'; candidateWikipedia?:string; candidateWikidata?:string; identityStatus:'Exact verified match'|'Strong probable match'|'Ambiguous'|'No reliable identity'|'Human verification required'; approved:boolean }
export interface ValidationResult { name:string; state:ValidationState; details:string }
export interface PageTypeResult { id:string; name:string; urlCount:number; patterns:string[]; sampleUrls:string[]; sampled:number; existingSchemas:string[]; recommendedSchemas:{type:string;level:'Required'|'Recommended'|'Conditional';reason:string}[]; coverage:number; status:'Covered'|'Partial'|'Missing'|'Needs review' }
export interface SiteAuditData { sitemapUrl:string; discoveredUrls:number; sampledUrls:number; pageTypes:PageTypeResult[]; schemaNodes:{id:string;label:string;kind:'site'|'page'|'schema'|'entity';status:'existing'|'recommended'|'missing';parent?:string}[] }
export interface Audit { id:string; projectName:string; url:string; domain:string; mode:string; auditedAt:string; isDemo:boolean; page:{title:string;h1:string;description:string;canonical:string;pageType:string;confidence:number;evidence:string[];alternate:string}; schemaItems:SchemaItem[]; requirements:Requirement[]; issues:Issue[]; entities:Entity[]; recommendation:Record<string,unknown>; validation:ValidationResult[]; executiveSummary:string[]; implementation:{priority:string;action:string;owner:string;effort:string;acceptance:string}[]; siteAudit?:SiteAuditData }
