const strip = (html='') => html.replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&nbsp;|&#160;/g,' ').replace(/&amp;/g,'&').replace(/\s+/g,' ').trim();
const pick = (html, re) => (html.match(re)?.[1] || '').replace(/<[^>]+>/g,' ').trim();
const absolute = (value, base) => { try { return new URL(value, base).href; } catch { return value || base; } };
const typesOf = node => Array.isArray(node?.['@type']) ? node['@type'] : node?.['@type'] ? [node['@type']] : ['Unknown'];
const collectTyped = value => { const found=[]; const visit=v=>{ if(!v||typeof v!=='object')return; if(v['@type'])found.push(v); Object.values(v).forEach(x=>Array.isArray(x)?x.forEach(visit):visit(x)); }; visit(value); return found; };

function classify(url,title,h1,text,types){
  const hay = `${url} ${title} ${h1} ${text.slice(0,2500)} ${types.join(' ')}`.toLowerCase();
  const rules = [
    ['Guide profile',/profile|tour guide|local guide|meet (your|the) guide|person/],['Tour detail page',/tour-detail|book now|availability|price|touristtrip|product/],
    ['Attraction page',/attraction|museum|landmark|historical building|touristattraction/],['City page',/city guide|things to do in|city|destination/],
    ['Blog article',/\/blog\/|blogposting|article|datepublished/],['Travel Guide',/travel guide|planning guide|itinerary/],['Tour listing or search-results page',/search|listing|collectionpage|itemlist/],
    ['Guide profile',/\/guide[s]?\//],['Contact page',/\/contact/],['About page',/\/about/]
  ];
  const match = rules.find(([,r])=>r.test(hay));
  if (match) return { pageType:match[0], confidence:82, alternate:'WebPage', evidence:[`URL/content pattern supports ${match[0]}.`, types.length ? `Existing types: ${types.join(', ')}.` : 'No existing schema type signal.'] };
  if (new URL(url).pathname === '/' || new URL(url).pathname === '') return {pageType:'Homepage',confidence:94,alternate:'WebPage',evidence:['The audited URL is the domain root.']};
  return {pageType:'Other',confidence:58,alternate:'Unknown',evidence:['No page-type pattern reached high confidence; human confirmation is required.']};
}

function requirementSet(pageType, domain, hasBreadcrumb){
  const base=[{schemaType:'WebPage',level:'Required for site model',ecosystem:'Schema.org semantics',properties:['@id','url','name','isPartOf','inLanguage'],reason:'Connects the canonical page to the site graph.'}];
  if(pageType==='Homepage') return [{schemaType:'Organization',level:'Required for site model',ecosystem:'Sitewide identity',properties:['@id','name','url','logo'],reason:'Stable publisher/business identity; include only verified data.'},{schemaType:'WebSite',level:'Required for site model',ecosystem:'Sitewide identity',properties:['@id','url','name','publisher','inLanguage'],reason:'Stable website node.'},...base];
  if(/Blog article|Travel Guide/.test(pageType)) return [...base,{schemaType:pageType==='Blog article'?'BlogPosting':'Article',level:'Required for Google eligibility',ecosystem:'Google-supported rich result',properties:['headline','image','author','datePublished','dateModified','mainEntityOfPage'],reason:'Article feature requirements; every value must be visible or verified.',prerequisite:'Visible author, dates and crawlable representative image.'},{schemaType:'BreadcrumbList',level:hasBreadcrumb?'Recommended':'Conditional',ecosystem:'Google-supported rich result',properties:['itemListElement'],reason:'Use only when visible breadcrumbs exist.'}];
  if(pageType==='Guide profile') return [...base,{schemaType:'ProfilePage',level:'Recommended',ecosystem:'Google-supported rich result',properties:['mainEntity','dateCreated','dateModified'],reason:'Represents a page primarily about a real person.'},{schemaType:'Person',level:'Required for site model',ecosystem:'Schema.org semantics',properties:['@id','name','image','description','knowsAbout','knowsLanguage'],reason:'Connect ProfilePage.mainEntity to a verified person node.'}];
  if(pageType==='Tour detail page') return [...base,
    {schemaType:'TouristTrip',level:'Recommended',ecosystem:'Schema.org semantics',properties:['name','description','touristType','itinerary','provider'],reason:'Travel-specific semantic description of the visible tour itinerary and audience.',prerequisite:'Use only details shown on the page.'},
    {schemaType:'Product',level:'Conditional',ecosystem:'Google-supported rich result',properties:['name','description','image','brand','offers'],reason:'Use when the tour is presented as a bookable product and the implementation follows Google product policies.',prerequisite:'Visible bookable product, image and commercial details.'},
    {schemaType:'Service',level:'Recommended',ecosystem:'Schema.org semantics',properties:['name','description','provider','areaServed','serviceType'],reason:'Represents the tour service and its provider.'},
    {schemaType:'Offer',level:'Conditional',ecosystem:'Schema.org semantics',properties:['url','price','priceCurrency','availability'],reason:'Connect through Product.offers only when exact live booking terms are visible.',prerequisite:'Visible price, currency and availability that stay synchronized with the page.'},
    {schemaType:'AggregateRating',level:'Conditional',ecosystem:'Google-supported rich result',properties:['ratingValue','reviewCount','bestRating','worstRating'],reason:'Summarises genuine first-party reviews for the specific tour.',prerequisite:'Visible aggregate rating and review count for this exact tour; never copy platform-wide ratings.'},
    {schemaType:'Review',level:'Conditional',ecosystem:'Google-supported rich result',properties:['author','datePublished','reviewBody','reviewRating','itemReviewed'],reason:'Marks up genuine reviews visibly displayed for this exact tour.',prerequisite:'The complete review, author and rating must be visible and comply with Google review policies.'},
    {schemaType:'BreadcrumbList',level:hasBreadcrumb?'Recommended':'Conditional',ecosystem:'Google-supported rich result',properties:['itemListElement'],reason:'Use only when visible breadcrumbs exist.'}
  ];
  if(/City page|Tour listing or search-results page/.test(pageType)) return [...base,
    {schemaType:'CollectionPage',level:'Required for site model',ecosystem:'Schema.org semantics',properties:['@id','name','about','mainEntity'],reason:'Represents the destination or search collection rather than an individual tour.'},
    {schemaType:'ItemList',level:'Conditional',ecosystem:'Schema.org semantics',properties:['itemListOrder','numberOfItems','itemListElement'],reason:'Maps the visible tour cards in their displayed order.',prerequisite:'Include only crawlable, canonical items visible in the rendered list.'},
    ...(pageType==='City page'?[{schemaType:'City',level:'Recommended',ecosystem:'Entity relationship',properties:['@id','name','sameAs'],reason:'Connect the exact destination through WebPage.about; sameAs requires identity approval.'}]:[]),
    {schemaType:'BreadcrumbList',level:hasBreadcrumb?'Recommended':'Conditional',ecosystem:'Google-supported rich result',properties:['itemListElement'],reason:'Use only when visible breadcrumbs exist.'}
  ];
  if(pageType==='Attraction page') return [...base,{schemaType:'TouristAttraction',level:'Recommended',ecosystem:'Entity relationship',properties:['@id','name','description','geo','sameAs'],reason:'Clarifies the exact attraction entity; exact identity verification is required.'},{schemaType:'Review',level:'Conditional',ecosystem:'Schema.org semantics',properties:['author','reviewBody','reviewRating','itemReviewed'],reason:'Use only for genuine visible reviews of this exact attraction.',prerequisite:'Visible review content and rating are required.'},{schemaType:'AggregateRating',level:'Conditional',ecosystem:'Schema.org semantics',properties:['ratingValue','reviewCount'],reason:'Use only when the page visibly displays an aggregate for this attraction.',prerequisite:'Visible rating value and review count are required.'},{schemaType:'BreadcrumbList',level:hasBreadcrumb?'Recommended':'Conditional',ecosystem:'Google-supported rich result',properties:['itemListElement'],reason:'Use only when visible breadcrumbs exist.'}];
  return [...base,{schemaType:'CollectionPage',level:'Recommended',ecosystem:'Schema.org semantics',properties:['@id','name','mainEntity'],reason:'Use when the page is visibly a collection or index.'},{schemaType:'ItemList',level:'Conditional',ecosystem:'Schema.org semantics',properties:['itemListElement'],reason:'Use only for a visible ordered or unordered list of canonical items.'},{schemaType:'BreadcrumbList',level:hasBreadcrumb?'Recommended':'Conditional',ecosystem:'Google-supported rich result',properties:['itemListElement'],reason:'Use only for visible breadcrumbs.'}];
}

function buildRecommendation(url,domain,page,reqs,visible){
  const slug=url.replace(/\/$/,''); const pageId=`${slug || domain}/#webpage`; const graph=[{'@type':'WebSite','@id':`${domain}/#website`,url:domain,name:'[VERIFIED SITE NAME REQUIRED]','publisher':{'@id':`${domain}/#organization`}},{'@type':'WebPage','@id':pageId,url,name:page.title||'[VISIBLE PAGE TITLE REQUIRED]','isPartOf':{'@id':`${domain}/#website`},inLanguage:'[VERIFIED PAGE LANGUAGE REQUIRED]'}];
  if(reqs.some(r=>r.schemaType==='Organization')) graph.unshift({'@type':'Organization','@id':`${domain}/#organization`,name:'[VERIFIED ORGANISATION NAME REQUIRED]',url:domain,logo:'[VERIFIED IMAGE URL REQUIRED]'});
  if(/Blog article|Travel Guide/.test(page.pageType)) graph.push({'@type':page.pageType==='Blog article'?'BlogPosting':'Article','@id':`${slug}/#article`,headline:page.title||'[VISIBLE HEADLINE REQUIRED]',mainEntityOfPage:{'@id':pageId},author:'[VISIBLE AUTHOR REQUIRED]',image:'[VERIFIED IMAGE URL REQUIRED]',datePublished:'[VISIBLE PUBLICATION DATE REQUIRED]'});
  if(page.pageType==='Guide profile') graph.push({'@type':'Person','@id':`${slug}/#person`,name:page.h1||'[VISIBLE PERSON NAME REQUIRED]',description:'[VISIBLE PROFILE DESCRIPTION REQUIRED]',sameAs:'[WIKIDATA IDENTITY REQUIRES APPROVAL]'});
  if(page.pageType==='Attraction page') graph.push({'@type':'TouristAttraction','@id':`${slug}/#place`,name:page.h1||page.title,mainEntityOfPage:{'@id':pageId},sameAs:'[WIKIDATA IDENTITY REQUIRES APPROVAL]'});
  return {'@context':'https://schema.org','@graph':graph};
}

export default async function handler(req,res){
  if(req.method!=='POST') return res.status(405).json({error:'Method not allowed'});
  try{
    const {url,projectName='Untitled Schema Audit'}=req.body||{}; if(!url) return res.status(400).json({error:'A URL is required.'});
    const target=/^https?:\/\//i.test(url)?url:`https://${url}`; const controller=new AbortController(); const timer=setTimeout(()=>controller.abort(),18000);
    const response=await fetch(target,{redirect:'follow',signal:controller.signal,headers:{'User-Agent':'SchemaEntityAuditor/1.0'}}); clearTimeout(timer);
    if(!response.ok) throw new Error(`The page returned HTTP ${response.status}.`); const html=await response.text();
    const title=pick(html,/<title[^>]*>([\s\S]*?)<\/title>/i); const h1=pick(html,/<h1[^>]*>([\s\S]*?)<\/h1>/i); const description=pick(html,/<meta[^>]+name=["']description["'][^>]+content=["']([^"']*)/i)||pick(html,/<meta[^>]+content=["']([^"']*)["'][^>]+name=["']description["']/i); const canonical=absolute(pick(html,/<link[^>]+rel=["']canonical["'][^>]+href=["']([^"']*)/i),target); const visible=strip(html); const domain=new URL(target).origin;
    const rawScripts=[...html.matchAll(/<script[^>]+type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi)].map(m=>m[1].trim()); const schemaItems=[]; const nodes=[];
    rawScripts.forEach((raw,i)=>{try{const parsed=JSON.parse(raw); const list=parsed?.['@graph']||[parsed]; const typed=collectTyped(parsed); typed.forEach(n=>nodes.push(n)); schemaItems.push({id:`schema_${i+1}`,format:'JSON-LD',type:[...new Set((typed.length?typed:list).flatMap(typesOf))],nodeId:parsed?.['@id'],properties:parsed,parseStatus:'Valid',googleEligibility:'Requires type-specific review',schemaValidity:'Pass',visibleMatch:'Needs review',errors:[],warnings:[]});}catch(e){schemaItems.push({id:`schema_${i+1}`,format:'JSON-LD',type:['Unknown'],properties:{raw},parseStatus:'Invalid',googleEligibility:'Not eligible while invalid',schemaValidity:'Fail',visibleMatch:'Needs review',errors:['Invalid JSON-LD syntax.'],warnings:[]});}});
    const existingTypes=[...new Set(nodes.flatMap(typesOf))]; const classified=classify(target,title,h1,visible,existingTypes); const hasBreadcrumb=/breadcrumb/i.test(visible)||existingTypes.includes('BreadcrumbList'); const reqs=requirementSet(classified.pageType,domain,hasBreadcrumb).map(r=>({...r,missing:r.properties.filter(p=>!nodes.some(n=>typesOf(n).includes(r.schemaType)&&n[p]!==undefined))}));
    const issues=[]; schemaItems.filter(s=>s.parseStatus==='Invalid').forEach((s,i)=>issues.push({id:`issue_parse_${i}`,severity:'Critical',category:'JSON-LD',title:'Invalid JSON-LD',evidence:`Schema block ${i+1} cannot be parsed.`,recommendation:'Correct JSON syntax before evaluating semantics.',scope:'URL'})); reqs.filter(r=>r.missing.length).forEach((r,i)=>issues.push({id:`issue_req_${i}`,severity:r.level.includes('Required')?'High':'Medium',category:'Missing markup',title:`${r.schemaType}: missing properties`,evidence:r.missing.join(', '),recommendation:r.prerequisite||`Add verified values for: ${r.missing.join(', ')}.`,scope:r.schemaType==='Organization'?'Sitewide':'Template'}));
    if(!rawScripts.length) issues.unshift({id:'issue_none',severity:'High',category:'Coverage',title:'No JSON-LD detected',evidence:'No application/ld+json script was extracted from the HTML response.',recommendation:'Implement a connected JSON-LD graph after verifying visible content and identities.',scope:'Template'});
    const primary=(h1||title).split(/[|–—:-]/)[0].trim(); const entities=primary?[{id:'entity_1',name:primary,type:/city|destination/i.test(classified.pageType)?'Place':'Thing',role:'Primary subject',evidence:h1?`Visible H1: ${h1}`:`Page title: ${title}`,salience:'High',property:classified.pageType==='Guide profile'?'mainEntity':'about',identityStatus:'Human verification required',approved:false}]:[];
    const recommendation=buildRecommendation(canonical||target,domain,{...classified,title,h1},reqs,visible); const placeholders=JSON.stringify(recommendation).match(/\[[A-Z][^\]]+\]/g)||[];
    const validation=[{name:'JSON-LD valid',state:schemaItems.some(s=>s.parseStatus==='Invalid')?'Fail':'Pass',details:schemaItems.length?'Existing JSON-LD parsed.':'No existing JSON-LD to validate.'},{name:'Schema.org valid',state:'Needs review',details:'Type/property semantics require vocabulary validation.'},{name:'Google-required fields complete',state:reqs.some(r=>r.level==='Required for Google eligibility'&&r.missing.length)?'Fail':'Needs review',details:'Evaluated separately from Schema.org validity.'},{name:'Entity identities verified',state:'Needs review',details:'sameAs is withheld until exact identity approval.'},{name:'Visible-content consistency passed',state:'Needs review',details:'Review extracted evidence before implementation.'},{name:'Production ready',state:placeholders.length?'Fail':'Needs review',details:placeholders.length?`${placeholders.length} unresolved placeholders remain.`:'Final QA required.'}];
    const audit={id:`audit_${Date.now()}`,projectName,url:target,domain,mode:'Single URL Audit',auditedAt:new Date().toISOString(),isDemo:false,page:{title,h1,description,canonical:canonical||target,...classified},schemaItems,requirements:reqs,issues,entities,recommendation,validation,executiveSummary:[`${classified.pageType} classification with ${classified.confidence}% confidence.`,`${schemaItems.length} structured-data block(s) extracted; ${schemaItems.filter(s=>s.parseStatus==='Invalid').length} invalid.`,`${issues.filter(i=>['Critical','High'].includes(i.severity)).length} high-priority issue(s) require attention.`,placeholders.length?'Recommended JSON-LD contains prerequisites and is not production ready.':'Recommended graph requires final human QA.'],implementation:issues.slice(0,8).map(i=>({priority:i.severity,action:i.recommendation,owner:i.scope==='Content prerequisite'?'Content':'Development / SEO',effort:i.severity==='Critical'?'Medium':'Low',acceptance:`${i.title} is resolved and independently validated.`}))};
    return res.status(200).json(audit);
  }catch(error){return res.status(500).json({error:error?.name==='AbortError'?'The page fetch timed out.':error?.message||'Audit failed.'});}
}
